language: node_js
node_js:
  - "12"
before_install:
  - npm i -g npm@6.12.0
  - cd ./backend/UserBusinessDatabase
script:
  - npm test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
